// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { id: string, provider: string, label: string, authKind: AccountAuthKind, scopes: Array<string>, expiresAt: number | null, createdAt: number, updatedAt: number, };

export type AccountAuthKind = "oauth" | "apikey";

/**
 * `audit_log` row (spec §4/§6, BL-22, task T18): every trust-choke-point decision, allow or
 * deny, surfaced to the Log/audit UI. `reason`/every other field NEVER carries secrets or
 * tool-call arguments (spec §6) — only the fixed action/decision/reason vocabulary
 * `crate::trust::authorize` writes (request content lives in the matching invocation's own
 * request-hash field, a sha256, never here).
 */
export type AuditRow = { id: string, at: number, 
/**
 * One of a fixed action-literal vocabulary (spec §4): a connect/disconnect, a stdio
 * process spawn, an MCP tool call, a direct-API connector invoke, a consent grant, or a
 * policy-cap denial.
 */
action: string, serverId: string | null, toolName: string | null, projectId: string | null, 
/**
 * `'allow'|'deny'`.
 */
decision: string, 
/**
 * e.g. consent required, tool disabled, rate limit exceeded, spend cap exceeded; `None` on
 * an `'allow'` row.
 */
reason: string | null, invocationId: string | null, };

/**
 * One operation a `ConnectorAdapter` (spec §7) exposes for a given account's provider.
 */
export type ConnectorOp = { name: string, description: string | null, };

/**
 * What context a stage's agent starts from (SCN-065). `inherit`: keep the current terminal's
 * context (the default WITHIN a terminal); `handoff`: start from the previous stage's outputs
 * (the default AT a terminal boundary, where the agent changes); `project`: start from the
 * project's own context only; `selected`: start from an owner-picked subset. Consumed by the S6b
 * executor — inert authoring config today.
 */
export type ContextScope = "inherit" | "handoff" | "project" | "selected";

/**
 * A per-project markdown document's DB-row half (SCN-054). Field set mirrors [`RuleSet`]
 * column-for-column minus the ruleset-only `scope`/`policy` (a doc is always project-scoped and
 * carries no policy) plus the owner-chosen `name` — the doc's identity within its project
 * (unique per project+name pair, validated against `[a-z0-9._-]`, never a path). NOTE: this doc
 * comment is copied into the generated TS verbatim by ts-rs, so field names here are camelCase
 * (`mdPath`/`mdHash`) — same discipline as [`StorageStatus`]'s doc.
 */
export type Doc = { id: string, projectId: string, name: string, mdPath: string, mdHash: string, createdAt: number, updatedAt: number, };

/**
 * `ListDocs`'s list-row shape (SCN-054: "the list shows name + last-modified"): name plus the
 * doc FILE's mtime in unix-ms, read fresh per list (files-as-truth — an external edit moves it
 * with no daemon write). When the file's mtime cannot be read (file lost/unreadable), the
 * dispatch layer falls back to the DB row's `updatedAt` — the last time orchd itself touched
 * the doc — rather than fabricating a timestamp.
 */
export type DocMeta = { name: string, modifiedAt: number, };

/**
 * `GetDoc`/`UpsertDoc`/`AcknowledgeDocFile`'s reply — mirrors [`RuleSetView`] field-for-field
 * (SCN-054 reuses the rules wire-state model wholesale): the DB row paired with a FRESH
 * read-state classification of the file at `doc.mdPath` against `doc.mdHash`. Reuses
 * [`RuleFileState`] verbatim — `ok` (healthy), `externallyModified` ("file changed externally"
 * with the Accept banner), and `missing` ("file lost" with the Recreate banner) are exactly the
 * three SCN-054 states, so a parallel enum would be pure drift surface.
 */
export type DocView = { doc: Doc, mdContent: string | null, fileState: RuleFileState, };

/**
 * named `DomainTask` to avoid the `tokio::task` clash (spec §4.2).
 */
export type DomainTask = { id: string, projectId: string, parentId: string | null, title: string, body: string, status: TaskStatus, 
/**
 * SCN-051 (ST-037): urgent/normal. `#[serde(default)]` (⇒ `Normal`) so pre-priority
 * payloads — a schema-≤v4 export bundle's task rows, or a frame from a pre-priority peer —
 * still decode instead of rejecting the whole bundle/frame; the daemon itself always sends
 * the field, so the generated TS type keeps it required.
 */
priority: TaskPriority, source: TaskSource, sourceId: string | null, tags: Array<string>, rank: number, rankAgent: number | null, rankAgentReasoning: string, createdAt: number, updatedAt: number, };

export type FitVerdict = "fit" | "noFit" | "unknown";

/**
 * Whether a stage advances on its own or waits for the operator (SCN-062). `auto`: the S6b
 * runtime continues to the next stage without a stop; `manual`: it pauses at a gate for an
 * explicit operator confirmation. Consumed by the S6b executor — inert authoring config today.
 */
export type Gate = "auto" | "manual";

export type Goal = { id: string, projectId: string, parentId: string | null, kind: GoalKind, title: string, body: string, ord: number, status: GoalStatus, metricRefs: Array<string>, createdAt: number, updatedAt: number, };

export type GoalKind = "strategic" | "additional";

export type GoalStatus = "active" | "achieved" | "dropped";

export type GraphEdge = { id: string, sourceNodeId: string, targetNodeId: string, kind: GraphEdgeKind, label: string, createdAt: number, };

export type GraphEdgeKind = "relates" | "depends" | "derives" | "supports" | "contradicts" | "parent";

export type GraphEntityType = "goal" | "idea" | "insight" | "task";

/**
 * Subgraph within N hops of a start node, cross-project (the agent retrieval query).
 */
export type GraphNeighborhood = { rootId: string, nodes: Array<GraphNode>, edges: Array<GraphEdge>, };

export type GraphNode = { id: string, projectId: string, kind: GraphNodeKind, entityType: GraphEntityType | null, entityId: string | null, label: string, body: string, posX: number, posY: number, createdAt: number, updatedAt: number, 
/**
 * `true` when this is an `entityRef` node whose referenced domain entity has been deleted
 * (D3 soft-ref orphan). Set by the read-time label resolver (`resolve_node_label` in
 * `crates/orchd/src/graph.rs`), never by the client — the UI renders an orphaned node with
 * «source deleted». Always `false` for non-`entityRef` nodes and for a still-live
 * `entityRef` node.
 */
isOrphan: boolean, };

export type GraphNodeKind = "concept" | "fact" | "artifact" | "decision" | "note" | "entityRef";

export type GraphView = { nodes: Array<GraphNode>, edges: Array<GraphEdge>, externalNodes: Array<GraphNode>, };

export type Idea = { id: string, projectId: string | null, title: string, body: string, lifecycle: IdeaLifecycle, createdAt: number, updatedAt: number, };

export type IdeaLifecycle = "captured" | "researching" | "specced" | "inDev" | "shipped" | "archived";

export type Insight = { id: string, projectId: string | null, source: string, title: string, body: string, fitVerdict: FitVerdict | null, fitReasoning: string, status: InsightStatus, resolutionReasoning: string, createdAt: number, updatedAt: number, };

export type InsightStatus = "new" | "accepted" | "archived";

/**
 * Durable tool-call result (spec §4: "untrusted by construction"). The untrusted flag is
 * always `true` for every artifact this Phase-1 slice creates — the S6b agent-boundary flag
 * this quarantines against, not something a client can ever clear via the wire.
 */
export type McpArtifact = { id: string, invocationId: string, 
/**
 * The MCP server that produced this artifact (`Some` for an `McpCallTool` result); `null`
 * for a `ConnectorInvoke` artifact, which carries the account instead (spec §4 XOR, D9; T12
 * review: ConnectorInvoke persists a durable untrusted artifact too). Exactly one is set.
 */
serverId: string | null, 
/**
 * The connector account that produced this artifact (`Some` for a `ConnectorInvoke` result);
 * `null` for an `McpCallTool`.
 */
accountId: string | null, toolName: string, projectId: string | null, 
/**
 * When the artifact was truncated at write time (BL-120), this is the truncated prefix —
 * `truncated` is then `Some(true)`.
 */
contentJson: string, contentText: string | null, isUntrusted: boolean, createdAt: number, 
/**
 * BL-120: `Some(true)` when the stored content was truncated at write time because it
 * exceeded the artifact content cap (the write-side guarantee that a `McpGetArtifact`/
 * `McpListArtifacts` frame stays under the wire's `MAX_FRAME_LEN`); `None` when whole.
 * Pre-BL-120 rows decode as `None` (the column backfills 0). Appended at the struct TAIL
 * with `#[serde(default)]` (append-only wire rule).
 */
truncated: boolean | null, };

export type McpAuthKind = "none" | "bearer" | "oauth";

/**
 * `OrchdRequest::McpCallTool` / `ConnectorInvoke`'s success payload (spec §5); the JSON result
 * is the tool's full structured output, already persisted as a durable artifact row.
 */
export type McpCallResult = { artifactId: string, invocationId: string, 
/**
 * The SAME content the artifact row stored — when the tool output exceeded the artifact
 * write-time cap (BL-120), this is the TRUNCATED form (`truncated` is then `Some(true)`),
 * so this response frame always fits the wire's `MAX_FRAME_LEN` instead of dropping the
 * connection outright.
 */
contentJson: string, isError: boolean, 
/**
 * BL-120: `Some(true)` when the call's content was truncated at artifact write time to keep
 * the frame encodable; `None` (and absent on pre-BL-120 peers' wires) when the content is
 * whole. Appended at the struct TAIL with `#[serde(default)]` (append-only wire rule).
 */
truncated: boolean | null, };

/**
 * `OrchdRequest::McpConnect`'s success payload (spec §5).
 */
export type McpConnectReport = { protocolVersion: string, toolCount: number, };

export type McpInvocation = { id: string, 
/**
 * The MCP server this call targeted (`Some` for an `McpCallTool` invocation); `null` for a
 * `ConnectorInvoke`, which carries the account instead (spec §4 XOR; T12 review:
 * ConnectorInvoke reuses this invocation record path). Exactly one of the two is set.
 */
serverId: string | null, 
/**
 * The connector account this call targeted (`Some` for a `ConnectorInvoke`); `null` for an
 * `McpCallTool`.
 */
accountId: string | null, toolName: string, projectId: string | null, 
/**
 * sha256 of args, NEVER the args themselves (spec §4: no arg content logged).
 */
requestHash: string, ok: boolean, errorKind: string | null, latencyMs: number, costUsd: number | null, inputTokens: number | null, outputTokens: number | null, startedAt: number, };

export type McpScope = "global" | "project";

export type McpServer = { id: string, name: string, transport: McpTransport, url: string | null, command: string | null, args: Array<string>, env: { [key in string]?: string }, scope: McpScope, projectId: string | null, authKind: McpAuthKind, secretRef: string | null, accountId: string | null, enabled: boolean, timeoutMs: number, maxRetries: number, 
/**
 * last negotiated MCP protocol version; `null` until first successful `McpConnect`.
 */
protocolVersion: string | null, createdAt: number, updatedAt: number, };

export type McpTool = { id: string, serverId: string, name: string, title: string | null, description: string | null, inputSchemaJson: string, enabled: boolean, fetchedAt: number, };

export type McpTransport = "http" | "stdio";

/**
 * `OrchdRequest::ConnectorBeginOAuth`'s success payload (spec §5): the PKCE authorize URL to
 * open in the browser, plus the CSRF `state` the subsequent `ConnectorCompleteOAuth` must echo.
 */
export type OAuthChallenge = { authorizeUrl: string, state: string, };

export type OrchdErrorCode = "notFound" | "invariant" | "validation" | "conflict" | "io" | "consent" | "policy";

/**
 * `policy` row (spec §4): a spend/rate cap at one of three scopes. `None` cap fields mean
 * "unlimited" for that dimension — a `Policy` with BOTH fields `None` is a legal (if pointless)
 * row. See [`PolicyScope`] for the scope/reference-id pairing rule.
 */
export type Policy = { id: string, scope: PolicyScope, 
/**
 * The project or server this policy applies to — `Some` for a project- or server-scoped
 * policy, `None` for the single global-scope policy (spec §4: null for global).
 */
refId: string | null, spendCapUsd: number | null, ratePerMin: number | null, createdAt: number, updatedAt: number, };

/**
 * Per-ruleset owner-consent policy (S1, spec §5.2). Strict-validated before storage (the
 * persistence `validate_policy` guard): `spendCapUsd >= 0`, non-empty confirmation-class and
 * allowed-path entries, and `deny_unknown_fields`.
 *
 * `supervisor` (SCN-046, A-7) is an ADDITIVE field carrying the per-project CEO config — see
 * [`SupervisorConfig`] for why it lives inside this policy rather than in its own table, and why
 * its `#[serde(default)]` matters for decoding rows/bundles that predate it. Because the field is
 * non-`Option`, an update that means to SET it must send it explicitly (same D11 discipline as the
 * two lists); the `default` only backfills DECODING, never a partial wire write.
 */
export type PolicyRules = { spendCapUsd: number | null, approvalClasses: Array<string>, pathAllowlist: Array<string>, supervisor: SupervisorConfig, };

/**
 * `policy.scope` (spec §4/§6, BL-22): which axis a cap applies to. `crate::trust`'s
 * effective-policy resolution (task T18) is MOST-SPECIFIC-wins — `Server` overrides `Project`
 * overrides `Global` — the whole matching row wins outright, not a per-field merge (see
 * `trust::resolve_policy`'s own doc comment for the full rationale).
 */
export type PolicyScope = "global" | "project" | "server";

export type Project = { id: string, name: string, description: string, status: ProjectStatus, 
/**
 * ordered, soft refs to sessiond
 */
workspaceIds: Array<string>, createdAt: number, updatedAt: number, };

export type ProjectStatus = "active" | "archived";

/**
 * `research_run` row (spec §4/§5, schema v4). The actual research artifact is the pre-existing
 * `McpArtifact` row a run's `tools/call` produces (D2) — this row is only the provenance link
 * plus status; `invocationId`/`artifactId` are `Some` only once the run reaches `done` (spec §4
 * CHECK linking status and the artifact reference).
 */
export type ResearchRun = { id: string, ideaId: string, serverId: string, toolName: string, argsJson: string, status: ResearchStatus, invocationId: string | null, artifactId: string | null, errorKind: string | null, createdAt: number, updatedAt: number, };

export type ResearchStatus = "pending" | "running" | "done" | "failed";

export type RuleFileState = "ok" | "missing" | "externallyModified";

export type RuleScope = "global" | "project";

export type RuleSet = { id: string, scope: RuleScope, projectId: string | null, mdPath: string, mdHash: string, policy: PolicyRules, createdAt: number, updatedAt: number, };

export type RuleSetView = { rule: RuleSet, mdContent: string | null, fileState: RuleFileState, };

/**
 * `fileState` is NOT itself a DB column — it is computed FRESH at read time by re-hashing the
 * SKILL.md file against its stored hash (files-as-truth, mirrors how `RuleSetView` covers the
 * `ruleset` table the same way). `Skill` intentionally has no `AcknowledgeRuleFile`-style verb to
 * clear a `Modified` state — this registry has no equivalent "I've seen the external edit"
 * affordance (out of scope for a plumbing-only slice), so re-adding (or, once a consumer exists,
 * re-registering) the skill is the only way to refresh the stored hash.
 */
export type Skill = { id: string, name: string, description: string, mdPath: string, mdHash: string, scope: SkillScope, projectId: string | null, fileState: SkillFileState, createdAt: number, updatedAt: number, };

/**
 * Files-as-truth read-time classification (mirrors `RuleFileState`'s role for `ruleset`, but a
 * distinct wire enum with its own — task-17-brief-specified — variant names): `Present` (the
 * file's current sha256 matches the stored hash), `Modified` (it exists but the hash no longer
 * matches — hand-edited or replaced outside orchd since it was registered), `Missing` (the file
 * is gone).
 */
export type SkillFileState = "present" | "modified" | "missing";

export type SkillScope = "global" | "project";

/**
 * One stage of a workflow (SCN-061). Order is the enclosing [`Workflow`]`.stages` Vec index —
 * there is no separate ordinal field, a reorder is a reordering of that Vec. `agent: None` means
 * the stage inherits the workflow's `defaultAgent` (SCN-061 "inherit"); `Some` pins a specific
 * known agent (validated against the known-agent set at save time). `skillIds` are the stage's
 * own skills — the effective set the S6b runtime would load is the workflow's global skills ∪
 * these (a pure view, never stored). `outputs` names the artifacts the stage is expected to
 * produce (free-form owner labels the S6b handoff logic will consume). `gate`/`contextScope`
 * carry the per-stage run behavior above.
 */
export type Stage = { id: string, name: string, prompt: string, skillIds: Array<string>, 
/**
 * `None` ⇒ inherit the workflow's `defaultAgent`; `Some` ⇒ a specific known agent.
 */
agent: string | null, contextScope: ContextScope, outputs: Array<string>, gate: Gate, };

export type StorageMode = "persistent" | "in_memory_fallback" | "recovered_from_corruption";

/**
 * Storage-degradation mode surfaced to the frontend (spec D3, BL-94). Fixed at boot: the daemon
 * either opened its on-disk DB normally (`Persistent`), fell back to a non-persistent in-memory
 * DB because the disk was unavailable (`InMemoryFallback`), or recovered from a corrupt on-disk
 * image that was quarantined aside (`RecoveredFromCorruption`, with `quarantinedPath` naming the
 * saved copy). Pulled once on connect and on every reconnect — there is no push, since the mode
 * never changes without a daemon restart.
 */
export type StorageStatus = { storageMode: StorageMode, quarantinedPath: string | null, };

/**
 * The per-project "CEO supervisor" config (SCN-046, FLW-19 JRN-10/#1, foundation §5 A-7). It
 * rides INSIDE [`PolicyRules`] as one additive field rather than a table of its own precisely
 * because A-7 says the CEO's authority is a view onto the existing policy: the caps it acts
 * within are the pre-existing policy `spendCapUsd` plus the approval-class machinery, never a
 * duplicate set of caps. This struct therefore carries only what the policy did not already model:
 * the enable switch, WHICH confirmation classes are delegated, the operator's free-form
 * instruction, and any extra rules.
 *
 * PLUMBING ONLY (honesty boundary, S6b). Persisting this config does NOT make a CEO act — the
 * orchestrator-agent runtime that would READ this config and autonomously answer agent questions
 * or continue workflows (SCN-047/SCN-049) does not exist yet (S6b). The UI carries a matching
 * pending note ("The CEO acts on this once the orchestrator agent runtime lands (S6b)."), the same
 * register as the Skills tab's registry banner. Nothing here starts an agent.
 *
 * `#[serde(default)]` at the container level lets a policy JSON blob that predates this field
 * (every ruleset policy row written before SCN-046, plus the DB's `'{}'` column default and any
 * older export bundle) decode straight into [`SupervisorConfig::default`] — a disabled CEO with an
 * empty scope — instead of failing with a "missing field" error. It also lets a partial object
 * (say `{"enabled":true}` from a hand-edited bundle) fill the rest from `Default` rather than
 * erroring, so a truncated blob degrades to "off" honestly.
 */
export type SupervisorConfig = { 
/**
 * Master switch, default `false` (SCN-046: "disabled by default until explicitly enabled").
 * An enabled CEO with an empty delegation scope is an invalid save (SCN-046: "empty delegation
 * scope with CEO on → blocked") — enforced client-side (the blocked alert) AND by the
 * persistence `validate_policy` guard, so the invariant holds even against a racing or
 * hand-crafted request, not just the UI.
 */
enabled: boolean, 
/**
 * The confirmation classes the operator has delegated to the CEO — the subset of the policy's
 * approval-class machinery the CEO is allowed to answer on the operator's behalf (SCN-046 step
 * 2). Each entry must be non-empty (validated alongside the policy's own list entries).
 */
delegatedClasses: Array<string>, 
/**
 * Free-form markdown the CEO must follow (SCN-046 step 3). Stored verbatim; never parsed here.
 */
instruction: string, 
/**
 * Optional extra CEO rules beyond the instruction — one editable line each (SCN-046
 * "custom-rules editor"). Each entry must be non-empty, same rule as the delegated classes.
 */
customRules: Array<string>, };

/**
 * SCN-051 (ST-037): two-level task priority. `Urgent` renders visually distinct (danger-tone
 * marker + chip) and sorts ahead of `Normal` within its status group (UI concern, SCN-051);
 * workflow continuation (SCN-049) consumes urgent tasks first. `Normal` is the single
 * contract-wide default — `#[default]` here backs the DB column default (`'normal'`), the
 * `#[serde(default)]` decode backfill on [`DomainTask::priority`], and the create-form default.
 */
export type TaskPriority = "urgent" | "normal";

export type TaskSource = "idea" | "insight" | "bug" | "plan";

export type TaskStatus = "backlog" | "todo" | "waiting" | "progress" | "testing" | "done";

/**
 * A reusable workflow definition (SCN-060/061/062/065), file-backed (files-as-truth, mirrors
 * `Skill`/`Doc`): the full definition is serialized to a JSON file under the app-support rules
 * tree, the DB row is the index, and `hash`/`fileState` give the same external-change honesty the
 * skill/doc registries have. `defaultAgent` is the fallback agent for every stage whose own
 * `agent` is `None`; it must be one of the known agents the app launches. `supervisor` REUSES the
 * wire `SupervisorConfig` (the per-workflow CEO-oversight config, same shape as the ruleset
 * policy's). `fileState` REUSES `SkillFileState` and is computed FRESH at read time (re-hashing
 * the JSON file at `jsonPath` against the stored `hash`), never a stored column. NOTE: this doc
 * comment is copied into the generated TS verbatim by ts-rs, so any field named here uses its
 * camelCase wire form (`projectId`/`defaultAgent`/`fileState`/…) — same discipline as [`Doc`]'s.
 */
export type Workflow = { id: string, name: string, description: string, scope: WorkflowScope, projectId: string | null, defaultAgent: string, stages: Array<Stage>, globalSkillIds: Array<string>, supervisor: SupervisorConfig, fileState: SkillFileState, jsonPath: string, hash: string, createdAt: number, updatedAt: number, };

/**
 * A workflow's scope (mirrors `SkillScope`/`RuleScope`): a `global` workflow is reusable across
 * every project; a `project` workflow belongs to one project (its `projectId` is then `Some`).
 */
export type WorkflowScope = "global" | "project";
