// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * named `DomainTask` to avoid the `tokio::task` clash (spec §4.2).
 */
export type DomainTask = { id: string, projectId: string, parentId: string | null, title: string, body: string, status: TaskStatus, source: TaskSource, sourceId: string | null, tags: Array<string>, rank: number, rankAgent: number | null, rankAgentReasoning: string, createdAt: number, updatedAt: number, };

export type FitVerdict = "fit" | "noFit" | "unknown";

export type Goal = { id: string, projectId: string, parentId: string | null, kind: GoalKind, title: string, body: string, ord: number, status: GoalStatus, metricRefs: Array<string>, createdAt: number, updatedAt: number, };

export type GoalKind = "strategic" | "additional";

export type GoalStatus = "active" | "achieved" | "dropped";

export type Idea = { id: string, projectId: string | null, title: string, body: string, lifecycle: IdeaLifecycle, createdAt: number, updatedAt: number, };

export type IdeaLifecycle = "captured" | "researching" | "specced" | "inDev" | "shipped" | "archived";

export type Insight = { id: string, projectId: string | null, source: string, title: string, body: string, fitVerdict: FitVerdict | null, fitReasoning: string, status: InsightStatus, resolutionReasoning: string, createdAt: number, updatedAt: number, };

export type InsightStatus = "new" | "accepted" | "archived";

export type OrchdErrorCode = "notFound" | "invariant" | "validation" | "conflict" | "io";

export type PolicyRules = { spendCapUsd: number | null, approvalClasses: Array<string>, pathAllowlist: Array<string>, };

export type Project = { id: string, name: string, description: string, status: ProjectStatus, 
/**
 * ordered, soft refs to sessiond
 */
workspaceIds: Array<string>, createdAt: number, updatedAt: number, };

export type ProjectStatus = "active" | "archived";

export type RuleFileState = "ok" | "missing" | "externallyModified";

export type RuleScope = "global" | "project";

export type RuleSet = { id: string, scope: RuleScope, projectId: string | null, mdPath: string, mdHash: string, policy: PolicyRules, createdAt: number, updatedAt: number, };

export type RuleSetView = { rule: RuleSet, mdContent: string | null, fileState: RuleFileState, };

export type TaskSource = "idea" | "insight" | "bug" | "plan";

export type TaskStatus = "backlog" | "todo" | "waiting" | "progress" | "testing" | "done";
