// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors a `command_events` row (Pv2 §7); ts-rs exported. First consumer is
 * `Request::GetCommandEvents` (spec §3.3), returned newest-first.
 */
export type CommandEvent = { sessionId: string, 
/**
 * monotonic per-session sequence number. `i64` maps to TS `bigint` by
 * default in ts-rs; overridden to `number` (matches `SessionMeta::created_at`).
 */
seq: number, 
/**
 * unix seconds. Overridden to TS `number` (see `seq` above).
 */
ts: number, 
/**
 * "started" | "finished" — the exact literals the Pv2 writer persists (pty_supervisor.rs)
 */
kind: string, exitCode: number | null, origin: string, };

/**
 * Internally tagged on `kind` (tag only, no content) — matches the TS discriminated
 * union in spec §5. Unit variants carry only `{ kind }`; the struct variant `Exited`
 * carries its fields flattened next to the tag.
 *
 * See the module-level "Dual-codec note" for why `Serialize`/`Deserialize` are
 * hand-written instead of derived: bincode cannot deserialize an internally-tagged
 * enum directly, but this type also crosses the bincode-framed Hop-B wire (nested in
 * `SessionMeta` / `Push::StateChanged`).
 */
export type SessionLifecycle = { "kind": "atPrompt" } | { "kind": "typing" } | { "kind": "running" } | { "kind": "exited", code: number | null, signal: string | null, };

export type SessionMeta = { id: string, workspaceId: string, title: string, shell: string, cwd: string, cols: number, rows: number, lifecycle: SessionLifecycle, waitingForInput: boolean, isActive: boolean, 
/**
 * unix seconds. `i64` maps to TS `bigint` by default in ts-rs; overridden to
 * `number` per spec §5 (safe for unix-second timestamps, well under 2^53).
 */
createdAt: number, };

/**
 * Hop-A Channel payload (spec §6.2). Adjacently tagged (`event`/`data`).
 * `Vec<u8>` serializes over Tauri IPC as `number[]`; ts-rs emits `Array<number>`.
 *
 * Purely a Hop-A (Tauri `Channel<TerminalEvent>`, JSON) type in production — it never
 * appears inside `Frame`/`Request`/`Response`/`Push` (the bincode-framed Hop-B wire;
 * see spec §7). It still gets the same dual-codec `Serialize`/`Deserialize` treatment
 * as `SessionLifecycle` (see the module-level "Dual-codec note") purely so it also
 * round-trips through bincode directly, for test parity / defense in depth.
 */
export type TerminalEvent = { "event": "replay", "data": { cols: number, rows: number, content: Array<number>, } } | { "event": "output", "data": { bytes: Array<number>, } };

export type Workspace = { id: string, name: string, 
/**
 * Compat mirror, always == roots[0].
 */
rootPath: string, 
/**
 * Ordered, equal roots; canonical absolute paths; len >= 1.
 */
roots: Array<string>, };
