//! Shell-integration assets + installer (spec §10.2). Spawns the user's REAL shell with a tiny,
//! non-invasive OSC-133/OSC-7 integration. zsh = ZDOTDIR redirect; bash = --init-file.

use std::io::Write;
use std::path::Path;

const BPA_ZSH: &str = include_str!("assets/bpa.zsh");
const BPA_BASH: &str = include_str!("assets/bpa-bash.sh");

/// Which shell family we are injecting into.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellKind {
    Zsh,
    Bash,
}

/// The concrete spawn recipe the supervisor (T9) uses to launch the shell with integration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShellSpawn {
    pub program: String,
    pub args: Vec<String>,
    pub env: Vec<(String, String)>,
}

/// Detect the shell family from an absolute shell path (basename match).
pub fn classify_shell(shell_path: &str) -> Option<ShellKind> {
    let base = Path::new(shell_path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    if base == "zsh" {
        Some(ShellKind::Zsh)
    } else if base == "bash" {
        Some(ShellKind::Bash)
    } else {
        None
    }
}

/// Materialize the integration assets into `runtime_dir` for one session and return the spawn
/// recipe.
/// - zsh: writes `<runtime_dir>/.zshenv` (the ZDOTDIR redirect stub that re-sources bpa.zsh),
///        copies `bpa.zsh` into `runtime_dir`, sets env ZDOTDIR=<runtime_dir> (+ BPA_ORIG_ZDOTDIR
///        carrying the caller's original ZDOTDIR when set) and BPA_INJECTION=1.
/// - bash: writes `<runtime_dir>/bpa-bash.sh`, returns args ["--init-file", "<that path>"] and env
///         BPA_INJECTION=1.
pub fn write_session_assets(runtime_dir: &Path, shell: ShellKind) -> std::io::Result<ShellSpawn> {
    std::fs::create_dir_all(runtime_dir)?;
    match shell {
        ShellKind::Zsh => {
            // Copy the integration script.
            let bpa_zsh_path = runtime_dir.join("bpa.zsh");
            std::fs::write(&bpa_zsh_path, BPA_ZSH)?;

            // Generate the ZDOTDIR .zshenv stub that restores the user's ZDOTDIR, re-sources their
            // rc, then sources our integration.
            let stub = format!(
                "# generated by write_session_assets (Builder Pro AI)\n\
                 if [ -n \"${{BPA_ORIG_ZDOTDIR-}}\" ]; then export ZDOTDIR=\"$BPA_ORIG_ZDOTDIR\"; else unset ZDOTDIR; fi\n\
                 [ -f \"${{ZDOTDIR:-$HOME}}/.zshenv\" ] && source \"${{ZDOTDIR:-$HOME}}/.zshenv\"\n\
                 [ -f \"${{ZDOTDIR:-$HOME}}/.zshrc\" ] && source \"${{ZDOTDIR:-$HOME}}/.zshrc\"\n\
                 source \"{}\"\n",
                bpa_zsh_path.display()
            );
            let mut f = std::fs::File::create(runtime_dir.join(".zshenv"))?;
            f.write_all(stub.as_bytes())?;

            let mut env = vec![
                ("ZDOTDIR".to_string(), runtime_dir.to_string_lossy().into_owned()),
                ("BPA_INJECTION".to_string(), "1".to_string()),
            ];
            // Carry the caller's original ZDOTDIR through so the stub can restore it.
            if let Some(orig) = std::env::var_os("ZDOTDIR") {
                env.push((
                    "BPA_ORIG_ZDOTDIR".to_string(),
                    orig.to_string_lossy().into_owned(),
                ));
            }
            Ok(ShellSpawn {
                program: "/bin/zsh".to_string(),
                args: vec![],
                env,
            })
        }
        ShellKind::Bash => {
            let script = runtime_dir.join("bpa-bash.sh");
            std::fs::write(&script, BPA_BASH)?;
            Ok(ShellSpawn {
                program: "/bin/bash".to_string(),
                args: vec![
                    "--init-file".to_string(),
                    script.to_string_lossy().into_owned(),
                ],
                env: vec![("BPA_INJECTION".to_string(), "1".to_string())],
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_known_shells() {
        assert_eq!(classify_shell("/bin/zsh"), Some(ShellKind::Zsh));
        assert_eq!(classify_shell("/usr/local/bin/zsh"), Some(ShellKind::Zsh));
        assert_eq!(classify_shell("/bin/bash"), Some(ShellKind::Bash));
        assert_eq!(classify_shell("/opt/homebrew/bin/bash"), Some(ShellKind::Bash));
        assert_eq!(classify_shell("/usr/bin/fish"), None);
    }

    #[test]
    fn zsh_assets_set_zdotdir_and_injection_env() {
        let dir = tempfile::tempdir().unwrap();
        let spawn = write_session_assets(dir.path(), ShellKind::Zsh).unwrap();
        // ZDOTDIR points at the runtime dir; BPA_INJECTION=1 present; no --init-file for zsh.
        assert!(spawn.args.is_empty(), "zsh takes no init args");
        let env: std::collections::HashMap<_, _> = spawn.env.iter().cloned().collect();
        assert_eq!(env.get("ZDOTDIR").map(String::as_str), Some(dir.path().to_str().unwrap()));
        assert_eq!(env.get("BPA_INJECTION").map(String::as_str), Some("1"));
        // The ZDOTDIR .zshenv stub and the copied bpa.zsh both exist.
        assert!(dir.path().join(".zshenv").is_file(), ".zshenv stub written");
        assert!(dir.path().join("bpa.zsh").is_file(), "bpa.zsh copied");
        // The stub sources the copied bpa.zsh by absolute path.
        let stub = std::fs::read_to_string(dir.path().join(".zshenv")).unwrap();
        assert!(stub.contains(dir.path().join("bpa.zsh").to_str().unwrap()),
            "stub must source the copied bpa.zsh absolute path");
        assert!(stub.contains("BPA_ORIG_ZDOTDIR"), "stub restores original ZDOTDIR");
    }

    #[test]
    fn bash_assets_use_init_file_and_injection_env() {
        let dir = tempfile::tempdir().unwrap();
        let spawn = write_session_assets(dir.path(), ShellKind::Bash).unwrap();
        let script = dir.path().join("bpa-bash.sh");
        assert_eq!(
            spawn.args,
            vec!["--init-file".to_string(), script.to_str().unwrap().to_string()]
        );
        let env: std::collections::HashMap<_, _> = spawn.env.iter().cloned().collect();
        assert_eq!(env.get("BPA_INJECTION").map(String::as_str), Some("1"));
        assert!(script.is_file(), "bpa-bash.sh written");
    }
}
