//! Shell-integration assets + installer (spec §10.2). Spawns the user's REAL shell with a tiny,
//! non-invasive OSC-133/OSC-7 integration. zsh = ZDOTDIR redirect; bash = --init-file.

use std::io::Write;
use std::path::Path;

const BPA_ZSH: &str = include_str!("assets/bpa.zsh");
const BPA_BASH: &str = include_str!("assets/bpa-bash.sh");

/// Which shell family we are injecting into.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellKind {
    Zsh,
    Bash,
}

/// The concrete spawn recipe the supervisor (T9) uses to launch the shell with integration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShellSpawn {
    pub program: String,
    pub args: Vec<String>,
    pub env: Vec<(String, String)>,
}

/// Detect the shell family from an absolute shell path (basename match).
pub fn classify_shell(shell_path: &str) -> Option<ShellKind> {
    let base = Path::new(shell_path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    if base == "zsh" {
        Some(ShellKind::Zsh)
    } else if base == "bash" {
        Some(ShellKind::Bash)
    } else {
        None
    }
}

/// Materialize the integration assets into `runtime_dir` for one session and return the spawn
/// recipe.
/// - zsh: writes `<runtime_dir>/.zshenv` (the ZDOTDIR redirect stub that re-sources bpa.zsh),
///   copies `bpa.zsh` into `runtime_dir`, sets env ZDOTDIR=<runtime_dir> (+ BPA_ORIG_ZDOTDIR
///   carrying the caller's original ZDOTDIR when set) and BPA_INJECTION=1.
/// - bash: writes `<runtime_dir>/bpa-bash.sh`, returns args ["--init-file", "<that path>"] and env
///   BPA_INJECTION=1.
pub fn write_session_assets(runtime_dir: &Path, shell: ShellKind) -> std::io::Result<ShellSpawn> {
    std::fs::create_dir_all(runtime_dir)?;
    match shell {
        ShellKind::Zsh => {
            // Copy the integration script.
            let bpa_zsh_path = runtime_dir.join("bpa.zsh");
            std::fs::write(&bpa_zsh_path, BPA_ZSH)?;

            // Generate the ZDOTDIR .zshenv stub that restores the user's ZDOTDIR, re-sources their
            // `.zshenv` (the .zshenv-time file), then sources our integration. We deliberately do
            // NOT source `~/.zshrc` here: zsh's own INTERACTIVE startup reads `~/.zshrc` once
            // (ZDOTDIR is restored to ~ below). The old stub sourced `.zshrc` here too, so it ran
            // TWICE (here at .zshenv time + again at interactive time) → duplicated prompt escape
            // sequences on the FIRST prompt render → "first couple of lines garbled, then normal".
            let stub = format!(
                "# generated by write_session_assets (Builder Pro AI)\n\
                 if [ -n \"${{BPA_ORIG_ZDOTDIR-}}\" ]; then export ZDOTDIR=\"$BPA_ORIG_ZDOTDIR\"; else unset ZDOTDIR; fi\n\
                 [ -f \"${{ZDOTDIR:-$HOME}}/.zshenv\" ] && source \"${{ZDOTDIR:-$HOME}}/.zshenv\"\n\
                 source \"{}\"\n",
                bpa_zsh_path.display()
            );
            let mut f = std::fs::File::create(runtime_dir.join(".zshenv"))?;
            f.write_all(stub.as_bytes())?;

            let mut env = vec![
                (
                    "ZDOTDIR".to_string(),
                    runtime_dir.to_string_lossy().into_owned(),
                ),
                ("BPA_INJECTION".to_string(), "1".to_string()),
            ];
            // Carry the caller's original ZDOTDIR through so the stub can restore it.
            if let Some(orig) = std::env::var_os("ZDOTDIR") {
                env.push((
                    "BPA_ORIG_ZDOTDIR".to_string(),
                    orig.to_string_lossy().into_owned(),
                ));
            }
            Ok(ShellSpawn {
                program: "/bin/zsh".to_string(),
                args: vec![],
                env,
            })
        }
        ShellKind::Bash => {
            let script = runtime_dir.join("bpa-bash.sh");
            std::fs::write(&script, BPA_BASH)?;
            Ok(ShellSpawn {
                program: "/bin/bash".to_string(),
                args: vec![
                    "--init-file".to_string(),
                    script.to_string_lossy().into_owned(),
                ],
                env: vec![("BPA_INJECTION".to_string(), "1".to_string())],
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_known_shells() {
        assert_eq!(classify_shell("/bin/zsh"), Some(ShellKind::Zsh));
        assert_eq!(classify_shell("/usr/local/bin/zsh"), Some(ShellKind::Zsh));
        assert_eq!(classify_shell("/bin/bash"), Some(ShellKind::Bash));
        assert_eq!(
            classify_shell("/opt/homebrew/bin/bash"),
            Some(ShellKind::Bash)
        );
        assert_eq!(classify_shell("/usr/bin/fish"), None);
    }

    #[test]
    fn zsh_assets_set_zdotdir_and_injection_env() {
        let dir = tempfile::tempdir().unwrap();
        let spawn = write_session_assets(dir.path(), ShellKind::Zsh).unwrap();
        // ZDOTDIR points at the runtime dir; BPA_INJECTION=1 present; no --init-file for zsh.
        assert!(spawn.args.is_empty(), "zsh takes no init args");
        let env: std::collections::HashMap<_, _> = spawn.env.iter().cloned().collect();
        assert_eq!(
            env.get("ZDOTDIR").map(String::as_str),
            Some(dir.path().to_str().unwrap())
        );
        assert_eq!(env.get("BPA_INJECTION").map(String::as_str), Some("1"));
        // The ZDOTDIR .zshenv stub and the copied bpa.zsh both exist.
        assert!(dir.path().join(".zshenv").is_file(), ".zshenv stub written");
        assert!(dir.path().join("bpa.zsh").is_file(), "bpa.zsh copied");
        // The stub sources the copied bpa.zsh by absolute path.
        let stub = std::fs::read_to_string(dir.path().join(".zshenv")).unwrap();
        assert!(
            stub.contains(dir.path().join("bpa.zsh").to_str().unwrap()),
            "stub must source the copied bpa.zsh absolute path"
        );
        assert!(
            stub.contains("BPA_ORIG_ZDOTDIR"),
            "stub restores original ZDOTDIR"
        );
        // The stub must NOT source `~/.zshrc` — zsh's interactive startup reads `~/.zshrc` itself
        // (ZDOTDIR restored to ~), so sourcing it here too made .zshrc run TWICE → duplicated
        // prompt escape sequences on the first prompt render → "first lines garbled, then normal".
        assert!(
            !stub.contains(".zshrc"),
            "stub must not source .zshrc (zsh reads it once at interactive startup; double-source garbles the first render)"
        );
    }

    #[test]
    fn bash_assets_use_init_file_and_injection_env() {
        let dir = tempfile::tempdir().unwrap();
        let spawn = write_session_assets(dir.path(), ShellKind::Bash).unwrap();
        let script = dir.path().join("bpa-bash.sh");
        assert_eq!(
            spawn.args,
            vec![
                "--init-file".to_string(),
                script.to_str().unwrap().to_string()
            ]
        );
        let env: std::collections::HashMap<_, _> = spawn.env.iter().cloned().collect();
        assert_eq!(env.get("BPA_INJECTION").map(String::as_str), Some("1"));
        assert!(script.is_file(), "bpa-bash.sh written");
    }

    use std::io::Read;
    use std::time::{Duration, Instant};

    // Spawn a shell through a raw PTY (via portable-pty) using the recipe from write_session_assets,
    // drive one command, and assert the emitted OSC bytes appear in the locked order.
    fn drive_shell_capture(kind: ShellKind, program: &str) -> Option<String> {
        drive_shell_capture_cmd(kind, program, b"printf hi\n")
    }

    // Same as `drive_shell_capture`, but lets the caller pick the driven command line (e.g. a
    // subshell-fronted command) instead of the default `printf hi`.
    fn drive_shell_capture_cmd(
        kind: ShellKind,
        program: &str,
        command_line: &[u8],
    ) -> Option<String> {
        use portable_pty::{native_pty_system, CommandBuilder, PtySize};
        if !std::path::Path::new(program).exists() {
            return None; // shell not installed on this box — skip
        }
        // NOTE: the runtime dir (ZDOTDIR for zsh) and HOME must be DISTINCT directories. The
        // generated `.zshenv` stub falls back to sourcing `${ZDOTDIR:-$HOME}/.zshenv` once it
        // restores/unsets ZDOTDIR; if HOME were the same directory as the runtime dir, that
        // fallback would source the stub itself again (infinite self-recursion / "recursion
        // limit exceeded"). A real session's runtime dir is never the user's actual $HOME, so a
        // separate `home_dir` here matches real usage and avoids that self-reference.
        let dir = tempfile::tempdir().unwrap();
        let home_dir = tempfile::tempdir().unwrap();
        let spawn = write_session_assets(dir.path(), kind).unwrap();

        let pty = native_pty_system();
        let pair = pty
            .openpty(PtySize {
                rows: 24,
                cols: 80,
                pixel_width: 0,
                pixel_height: 0,
            })
            .unwrap();
        let mut cmd = CommandBuilder::new(program);
        cmd.env_clear();
        cmd.env("TERM", "xterm-256color");
        cmd.env(
            "PATH",
            std::env::var("PATH").unwrap_or_else(|_| "/usr/bin:/bin".into()),
        );
        cmd.env("HOME", home_dir.path().to_string_lossy().into_owned());
        cmd.env("HOSTNAME", "localhost");
        cmd.env("HOST", "localhost");
        for (k, v) in &spawn.env {
            cmd.env(k, v);
        }
        for a in &spawn.args {
            cmd.arg(a);
        }
        cmd.cwd(dir.path());
        let mut child = pair.slave.spawn_command(cmd).unwrap();
        drop(pair.slave);

        let mut reader = pair.master.try_clone_reader().unwrap();
        let mut writer = pair.master.take_writer().unwrap();

        // Collect output on a thread until we see a D mark or time out.
        let (tx, rx) = std::sync::mpsc::channel::<Vec<u8>>();
        std::thread::spawn(move || {
            let mut buf = [0u8; 4096];
            while let Ok(n) = reader.read(&mut buf) {
                if n == 0 {
                    break;
                }
                if tx.send(buf[..n].to_vec()).is_err() {
                    break;
                }
            }
        });

        // Give the shell time to print its first prompt (A/B/OSC7), then run one command.
        std::thread::sleep(Duration::from_millis(400));
        writer.write_all(command_line).unwrap();
        writer.flush().unwrap();

        let start = Instant::now();
        let mut acc: Vec<u8> = Vec::new();
        while start.elapsed() < Duration::from_secs(6) {
            if let Ok(chunk) = rx.recv_timeout(Duration::from_millis(200)) {
                acc.extend_from_slice(&chunk);
                // Stop only once we have seen BOTH a C mark (our command was dispatched) and a
                // SUBSEQUENT D mark (that command finished). The very first prompt (shell
                // startup) already emits its own D/A/OSC7 cycle before we ever send `printf hi`,
                // so gating on "any D" alone stops the capture too early — before the typed
                // command's own C/D pair (and the OSC 7 emitted with its prompt) ever arrives.
                if let Some(c_pos) = acc.windows(7).position(|w| w == b"\x1b]133;C") {
                    if acc[c_pos..].windows(7).any(|w| w == b"\x1b]133;D") {
                        break;
                    }
                }
            }
        }
        let _ = child.kill();
        let s = String::from_utf8_lossy(&acc).into_owned();
        if std::env::var_os("BPA_DEBUG_TEST").is_some() {
            eprintln!("CAPTURED[{kind:?}]: {s:?}");
        }
        Some(s)
    }

    fn assert_osc_order(out: &str) {
        // The capture spans TWO prompt cycles: the shell's own startup prompt (emitted before we
        // ever type anything) and the cycle for the `printf hi` command we drive. The very first
        // `D` in the whole capture belongs to the STARTUP cycle (it closes the implicit "startup"
        // pseudo-command), so ordering must be checked relative to `C` (which only ever appears
        // once we actually dispatch a real command) rather than by first-occurrence-anywhere.
        //
        // Order within the driven command's cycle: A (prompt) < B (prompt end) < C (exec) <
        // D (done), where A/B/C are the LATEST occurrences at-or-before C's cycle and D is the
        // first occurrence AFTER C.
        let c = out.find("\x1b]133;C").expect("OSC 133;C present");
        let a = out[..c]
            .rfind("\x1b]133;A")
            .expect("OSC 133;A present before C");
        let b = out[..c]
            .rfind("\x1b]133;B")
            .expect("OSC 133;B present before C");
        let d = c + out[c..]
            .find("\x1b]133;D")
            .expect("OSC 133;D present after C");
        assert!(out.contains("\x1b]7;file://"), "OSC 7 cwd present");
        // Order within one prompt+command cycle: A (prompt) < B (prompt end) < C (exec) < D (done).
        assert!(a < c, "A must precede C ({a} < {c})");
        assert!(b < c, "B must precede C ({b} < {c})");
        assert!(c < d, "C must precede D ({c} < {d})");
    }

    #[test]
    fn zsh_emits_osc_sequence_in_order() {
        match drive_shell_capture(ShellKind::Zsh, "/bin/zsh") {
            Some(out) => assert_osc_order(&out),
            None => eprintln!("skipping zsh OSC test: /bin/zsh not present"),
        }
    }

    #[test]
    fn bash_emits_osc_sequence_in_order() {
        match drive_shell_capture(ShellKind::Bash, "/bin/bash") {
            Some(out) => assert_osc_order(&out),
            None => eprintln!("skipping bash OSC test: /bin/bash not present"),
        }
    }

    // Count occurrences of a byte-string marker in `out` (non-overlapping-window scan; markers
    // never overlap themselves so this is exact).
    fn count_occurrences(out: &str, marker: &str) -> usize {
        out.as_bytes()
            .windows(marker.len())
            .filter(|w| *w == marker.as_bytes())
            .count()
    }

    // Regression test for the bash DEBUG-trap subshell blind spot: bash does NOT propagate the
    // DEBUG trap into a subshell `(...)` unless `set -o functrace` (`set -T`) is enabled. A
    // top-level command whose form is a subshell — e.g. `(exit 37)` — must still emit exactly one
    // `133;C` (command-running marker), followed by `133;D;37` (the subshell's exit code). Before
    // the fix (no `set -o functrace` in bpa-bash.sh), the DEBUG trap never fires inside `(...)`,
    // so `133;C` never appears for this whole class of real, common commands (subshells, e.g.
    // `(cd /tmp && echo hi)`, `(export X=1; cmd)`) — breaking the `Running` lifecycle state
    // (spec §10.3) and `waiting_for_input` (§10.4) for them.
    #[test]
    fn bash_subshell_command_emits_c_exactly_once_then_correct_exit_code() {
        match drive_shell_capture_cmd(ShellKind::Bash, "/bin/bash", b"(exit 37)\n") {
            Some(out) => {
                // Exactly one `133;C` for this single top-level subshell command (functrace must
                // not cause the guarded-once semantics to double-fire across the subshell's own
                // simple commands).
                let c_count = count_occurrences(&out, "\x1b]133;C");
                assert_eq!(
                    c_count, 1,
                    "expected exactly one OSC 133;C for `(exit 37)`, got {c_count} in {out:?}"
                );
                let c = out
                    .find("\x1b]133;C")
                    .expect("OSC 133;C present for subshell command");
                // The exit code 37 from the subshell must be captured in the following D mark.
                let d_rel = out[c..]
                    .find("\x1b]133;D;37\x07")
                    .expect("OSC 133;D;37 present after C for `(exit 37)`");
                assert!(d_rel > 0, "D must come strictly after C");
            }
            None => eprintln!("skipping bash subshell functrace test: /bin/bash not present"),
        }
    }

    // Guard against functrace over-firing: an ordinary pipeline (multiple simple commands joined
    // by `|`) is still ONE top-level command and must still yield exactly one `133;C`, not one per
    // pipeline stage. This must stay green after enabling `set -o functrace`.
    #[test]
    fn bash_pipeline_command_emits_c_exactly_once() {
        match drive_shell_capture_cmd(ShellKind::Bash, "/bin/bash", b"echo hi | cat | cat\n") {
            Some(out) => {
                let c_count = count_occurrences(&out, "\x1b]133;C");
                assert_eq!(
                    c_count, 1,
                    "expected exactly one OSC 133;C for a 3-stage pipeline, got {c_count} in {out:?}"
                );
            }
            None => eprintln!("skipping bash pipeline no-double-C test: /bin/bash not present"),
        }
    }
}
