/**
 * Central UI copy registry (spec D1, O-2). Single source of every user-facing string in the
 * webview — English-only, no runtime i18n framework, no locale switch (YAGNI: the standing rule is
 * "always English", not "translatable"). Every component references a key here
 * (`strings.research.run`) instead of an inline literal, and component tests assert against these
 * same keys so copy changes never silently break a test.
 *
 * Grouped by surface area. Leaf values are English strings; parameterized copy is a function
 * `(x) => `…${x}…``. Rust-side user-facing strings have no equivalent here — they are translated in
 * place (spec D1).
 */
export const strings = {
  // ── generic, reused across surfaces ──────────────────────────────────────────────────────────
  common: {
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    create: "Create",
    add: "Add",
    retry: "Retry",
    close: "Close",
    update: "Update",
    accept: "Accept",
    moveUp: "Move up",
    moveDown: "Move down",
    descriptionOptional: "description (optional)",
    noVerdict: "— no verdict —",
    argsInvalidJson: "arguments must be valid JSON",
    /** Policy scope labels, shared by the research run dialog and the extensions log tab. */
    scope: { global: "global", project: "project", server: "server" },
  },

  // ── error mapping: orchd, filesystem, and daemon command errors ──────────────────────────────
  errors: {
    invariant: (msg: string) => `invalid operation: ${msg}`,
    conflict: (msg: string) => `conflict: ${msg}`,
    notFound: "not found",
    validation: (msg: string) => `invalid data: ${msg}`,
    io: (msg: string) => `service error: ${msg}`,
    consent: (msg: string) => `connection consent required: ${msg}`,
    policy: (msg: string) => `blocked by policy: ${msg}`,
    orchdError: "orchestrator error",
    unavailable: "orchestrator unavailable",
    unknown: "unknown orchestrator error",
    /** `describeFsError` branches (FilePreview, FileTree). */
    fs: {
      notFound: "file not found",
      noAccess: "access denied",
      outsideRoot: "path is outside the workspace root",
      tooLarge: "file is too large",
      alreadyExists: "a file with this name already exists",
      io: "I/O error",
    },
    /** `describeCommandError` branches (FileTree). */
    command: {
      daemon: "daemon error",
      disconnected: "daemon disconnected",
      internal: "internal error",
      incompatible: "daemon incompatible — update required",
      failed: "operation failed",
      tooLarge: "request too large",
    },
  },

  // ── chrome: banners, upgrade dialog, sidebar, toasts ─────────────────────────────────────────
  chrome: {
    daemonOutdated: "Background service is outdated — update required",
    orchdUnavailable: "Orchestrator unavailable",
    upgrade: {
      required: "Update required",
      daemonDetail: (n: number) =>
        `Update the background service — ${n} live sessions will end. Their records and scrollback are saved and will reappear as inactive.`,
      daemonDetailAll:
        "Update the background service — all of its live sessions will end. Their records and scrollback are saved and will reappear as inactive.",
      daemonRestartFailed: (err: string) =>
        `Failed to restart the background service: ${err}. Check permissions (launchctl) and try again.`,
      orchdBody: "Update the orchestrator background service — records (projects, goals, tasks) are saved",
      orchdRestartFailed: (err: string) =>
        `Failed to restart the orchestrator background service: ${err}. Check permissions (launchctl) and try again.`,
    },
    sidebar: {
      extensions: "Extensions",
      extensionsNav: "⚙ Extensions",
      noProject: "No project",
      linkToProject: (name: string) => `Link ${name} to a project`,
      linkPlaceholder: "link…",
      addProject: "+ project",
    },
  },

  // ── Home (attention-first view + goals rail) ─────────────────────────────────────────────────
  home: {
    running: "running",
    atPrompt: "at prompt",
    exited: "exited",
    exitedWithError: "exited with error",
    waitingForInput: "waiting for input",
    noActiveSessions: "No active sessions.",
    openWorkspace: (name: string) => `Open ${name}`,
    needsYou: "Needs you",
    go: "Go →",
    runningSection: "Running",
    recentlyFinished: "Recently finished",
    ok: "success",
    withError: "with error",
    goals: "Goals",
    goalsLoading: "Goals are loading…",
  },

  // ── files: rail, tree, preview ───────────────────────────────────────────────────────────────
  files: {
    openPanel: "Open the file panel",
    collapsePanel: "Collapse the file panel",
    title: "Files",
    showIgnored: "show ignored",
    liveUpdatesPaused: "live updates paused — refresh",
    loading: "Loading…",
    fileWord: "file",
    folderWord: "folder",
    readFolderFailed: (msg: string) => `Failed to read folder: ${msg}`,
    refreshFolderFailed: (msg: string) => `Failed to refresh folder: ${msg}`,
    createFailed: (what: string, msg: string) => `Failed to create ${what}: ${msg}`,
    renameFailed: (msg: string) => `Failed to rename: ${msg}`,
    deleteConfirm: (label: string, rel: string) =>
      `Delete ${label} "${rel}"? It will be moved to the Trash.`,
    deleteFailed: (msg: string) => `Failed to delete: ${msg}`,
    revealFailed: (msg: string) => `Failed to reveal in Finder: ${msg}`,
    openExternalFailed: (msg: string) => `Failed to open in external app: ${msg}`,
    addRootFailed: (msg: string) => `Failed to add root: ${msg}`,
    menuAria: (name: string) => `Menu: ${name}`,
    actionsAria: (name: string) => `Actions: ${name}`,
    newFile: "New file",
    newFolder: "New folder",
    rename: "Rename",
    reveal: "Show in Finder",
    openExternal: "Open in external app",
    newFileNamePlaceholder: "New file name",
    newFolderNamePlaceholder: "New folder name",
    newNamePlaceholder: "New name",
    openFileFailed: (msg: string) => `Failed to open file: ${msg}`,
    selectFile: "Select a file to preview",
    binaryFile: (size: string) => `Binary file · ${size}`,
    tooLargePreview: (size: string) => `File too large to preview · ${size}`,
    contentMayHaveChanged:
      "The content may have changed while reading — a partial result is shown.",
  },

  // ── terminal + command-history strip ─────────────────────────────────────────────────────────
  terminal: {
    fileOutsideWorkspace: "file is outside the workspace or not found",
    commandHistory: "Command history",
    noCommands: "No commands yet",
    loadHistoryFailed: "Failed to load command history",
    interrupted: "interrupted",
    interruptedTitle: "Interrupted — the session ended before the command finished",
  },

  // ── project panel + create-project dialog ────────────────────────────────────────────────────
  project: {
    workspaceRequired: "at least one workspace is required",
    createWorkspaceFailed: "failed to create workspace",
    projectCreated: "Project created",
    newProject: "New project",
    nameLabel: "Name",
    nameAria: "Project name",
    descriptionLabel: "Description",
    descriptionAria: "Project description",
    noFreeWorkspaces: "no available workspaces",
    createWorkspace: "+ create workspace",
    tabs: {
      overview: "Overview",
      goals: "Goals",
      ideas: "Ideas",
      tasks: "Tasks",
      insights: "Insights",
      rules: "Rules",
      graph: "Graph",
    },
    loading: "Loading project…",
    jsonCopied: "JSON copied",
    exportedToFile: "Exported to file",
    importSummary: (r: { projects: number; goals: number; ideas: number; insights: number; tasks: number }) =>
      `Imported: projects ${r.projects}, goals ${r.goals}, ideas ${r.ideas}, insights ${r.insights}, tasks ${r.tasks}`,
    workspaceUnavailable: "workspace unavailable",
    unlink: "Unlink",
    addWorkspaceAria: "Add workspace",
    addWorkspaceOption: "+ add workspace…",
    exportLabel: "Export",
    copyJson: "Copy JSON",
    saveToFile: "Save to file…",
    importLabel: "Import",
    importFromFile: "Import from file…",
    noJsonFiles: "No .json files in the selected folder",
  },

  // ── goal tree ────────────────────────────────────────────────────────────────────────────────
  goals: {
    status: { active: "active", achieved: "achieved", dropped: "dropped" },
    deleteConfirm: "delete the entire branch?",
    newSubgoal: "new goal",
    titleAria: "Goal title",
    statusAria: "Goal status",
    addSubgoal: "+ subgoal",
    empty: "The goal tree is empty.",
    treeAria: "Goal tree",
  },

  // ── quick capture (⌘K new idea) ──────────────────────────────────────────────────────────────
  capture: {
    ideaSaved: "idea saved",
    newIdea: "New idea",
    titleAria: "Idea title",
    titlePlaceholder: "title",
    descriptionAria: "Idea description",
    projectAria: "Project",
    noProject: "no project",
  },

  // ── ruleset panel ────────────────────────────────────────────────────────────────────────────
  rules: {
    missingBanner: "file lost",
    modifiedBanner: "file changed externally",
    spendCapNotNumber: "spend cap must be a number",
    spendCapNegative: "spend cap cannot be negative",
    emptyEntry: "empty entries are not allowed",
    deleteEntry: (v: string) => `Delete ${v}`,
    addEntry: "+ add",
    loading: "Loading rules…",
    revealFile: "reveal file",
    recreate: "Recreate",
    contentAria: "Rules content",
    spendCapLabel: "Spend cap, $",
    spendCapAria: "Spend cap in dollars, empty — no limit",
    spendCapPlaceholder: "no limit",
    confirmClassesLabel: "Classes requiring confirmation",
    confirmClassAria: "New confirmation class",
    confirmClassPlaceholder: "class",
    allowedPathsLabel: "Allowed paths",
    allowedPathAria: "New allowed path",
    allowedPathPlaceholder: "path",
    savePolicy: "Save policy",
  },

  // ── ideas list (+ spawn-project flow) ────────────────────────────────────────────────────────
  ideas: {
    deleteConfirm: "delete idea?",
    lifecycle: {
      captured: "captured",
      researching: "researching",
      specced: "specced",
      inDev: "in development",
      shipped: "shipped",
      archived: "archived",
    },
    titleAria: "Idea title",
    stageAria: "Idea stage",
    research: "Research",
    hideResearch: "hide research",
    researchCount: (n: number) => `research (${n})`,
    descriptionAria: "Idea description",
    linkToProjectAria: "Link to project",
    selectProject: "select a project…",
    linkToProject: "link to project",
    newTitleAria: "New idea title",
    newTitlePlaceholder: "idea title",
    newDescriptionAria: "New idea description",
    addIdea: "+ idea",
    emptyOrphan: "No ideas without a project.",
    emptyProject: "No ideas in this project yet.",
    spawn: {
      folderPickerFailed: "failed to open the folder picker",
      createdFromIdea: "Project created from idea",
      createProject: "Create project",
    },
  },

  // ── research (run dialog + status pane) ──────────────────────────────────────────────────────
  research: {
    runStatus: { pending: "pending", running: "running", done: "done", failed: "failed" },
    runStarted: "Research run started",
    dialogTitle: (title: string) => `Research "${title}"`,
    serverLabel: "Server",
    serverAria: "MCP server",
    selectServer: "select a server…",
    toolLabel: "Tool",
    toolAria: "Tool",
    selectTool: "select a tool…",
    argsLabel: "Arguments (JSON)",
    argsAria: "Call arguments",
    limitScope: "limit scope:",
    notSet: "not set",
    spendCap: "spend cap:",
    callsPerMin: "calls/min limit:",
    costNote:
      "the cost of an external call is usually unknown in advance — the orchestrator will stop the call only if it exceeds the current limit.",
    run: "Run",
    emptyRuns: "no research for this idea yet",
    showArtifact: "show artifact",
    formInsight: "Form insight",
    formInsightNoResearch: "form insight without research",
    unknownError: "unknown error",
  },

  // ── insights list + form-insight dialog ──────────────────────────────────────────────────────
  insights: {
    archiveReasonRequired: "an archive reason is required",
    fitVerdict: { fit: "fit", noFit: "no fit", unknown: "unclear" },
    status: { new: "new", accepted: "accepted", archived: "archived" },
    statusAria: "Insight status",
    sourceLabel: "source:",
    archiveReasonAria: "Archive reason",
    archiveReasonPlaceholder: "archive reason",
    confirmArchival: "confirm archival",
    ownerVerdictAria: "Owner verdict",
    verdictReasoningAria: "Verdict reasoning",
    verdictReasoningPlaceholder: "reasoning",
    applyVerdict: "apply verdict",
    emptyOrphan: "No insights without a project.",
    emptyProject: "No insights in this project yet.",
    form: {
      created: "Insight created",
      addedToBacklog: "Task added to backlog",
      title: "Form insight",
      nameLabel: "Name",
      nameAria: "Insight title",
      descriptionLabel: "Description",
      descriptionAria: "Insight description",
      ownerVerdictLabel: "Owner verdict",
      ownerVerdictAria: "Owner verdict",
      reasoningLabel: "Reasoning",
      reasoningAria: "Verdict reasoning",
      status: (status: string) => `insight status: ${status}`,
      contextTitle: "Assessment context",
      ideaNotLinked: "the idea is not linked to a project — context unavailable",
      projectGoals: "Project goals",
      noGoals: "no goals yet",
      metrics: (m: string) => ` — metrics: ${m}`,
      relatedGraph: "Related graph",
      noGraphNode: "no graph node for this idea yet",
      noRelatedNodes: "no related nodes",
      toBacklog: "To backlog",
    },
  },

  // ── tasks list ───────────────────────────────────────────────────────────────────────────────
  tasks: {
    status: {
      backlog: "backlog",
      todo: "to do",
      waiting: "waiting",
      progress: "in progress",
      testing: "testing",
      done: "done",
    },
    source: { idea: "idea", insight: "insight", bug: "bug", plan: "plan" },
    deleteConfirm: "delete task?",
    deleteConfirmWithChildren: (n: number) => `delete task? will delete ${n} subtasks`,
    statusAria: "Task status",
    newTitleAria: "New task title",
    newTitlePlaceholder: "task title",
    newDescriptionAria: "New task description",
    newSourceAria: "New task source",
    parentAria: "Parent task",
    noParent: "no parent",
    newTagsAria: "New task tags (comma-separated)",
    tagsPlaceholder: "comma-separated tags",
    addTask: "+ task",
    empty: "no tasks",
  },

  // ── graph canvas ─────────────────────────────────────────────────────────────────────────────
  graph: {
    newNodeLabel: "New node",
    deleteConfirm: "delete selection?",
    sourceRemoved: "source removed",
    newNodeTypeAria: "New node type",
    deleteSelection: "Delete selection",
    searchAria: "Search the graph",
    searchPlaceholder: "search…",
    empty: "empty",
  },

  // ── extensions view (all ext/* tabs) ─────────────────────────────────────────────────────────
  ext: {
    panelTitle: "Extensions",
    unverified: "⚠ unverified data",
    invoke: "invoke",
    delete: "delete",
    projectSoon: "project (soon)",
    tabs: {
      servers: "Servers",
      tools: "Tools",
      connectors: "Connectors",
      log: "Log",
      artifacts: "Artifacts",
      skills: "Skills",
    },
    artifacts: {
      projectLabel: "project:",
      toggleHide: "hide",
      toggleShow: "show content",
      empty: "no artifacts",
    },
    connectDialog: {
      title: (name: string) => `Connect to server "${name}"`,
      body: "The app will connect to this MCP server and gain access to its tools.",
      connect: "Connect",
    },
    connectors: {
      apiKeyLabel: "API key",
      accountConnected: "Account connected",
      deleteConfirm: (label: string) => `delete account "${label}"?`,
      accountsTitle: "Accounts",
      noAccounts: "no accounts",
      scopesLabel: "scopes:",
      expiresLabel: "expires:",
      operationFor: (label: string) => `Operation for ${label}`,
      operationOption: "— operation —",
      argsFor: (label: string) => `Arguments for ${label}`,
      operationError: "the operation returned an error",
      addApiKeyTitle: "Add API key",
      providerAria: "Provider",
      providerPlaceholder: "provider",
      labelAria: "Label",
      labelPlaceholder: "label",
      apiKeyAria: "API key",
      apiKeyPlaceholder: "API key",
      addApiKey: "+ API key",
      connectOAuthTitle: "Connect OAuth",
      scopesAria: "Scopes",
      scopesPlaceholder: "scopes, comma-separated (optional)",
      startOAuth: "start OAuth",
      openAuthPage: "open authorization page",
      codeAria: "Authorization code",
      codePlaceholder: "paste the code from the redirect",
      finish: "finish",
    },
    servers: {
      authKind: { none: "no authorization", bearer: "bearer token", oauth: "OAuth (soon)" },
      deleteConfirm: (name: string) => `delete server "${name}"?`,
      tokenSaved: "Token saved",
      nameAria: "Server name",
      namePlaceholder: "name",
      transportAria: "Transport",
      stdioSoon: "stdio (soon)",
      urlAria: "Server URL",
      scopeAria: "Scope",
      authAria: "Authorization",
      addServer: "+ server",
      empty: "no servers",
      protocol: (v: string) => `protocol ${v}`,
      notConnected: "not yet connected",
      disable: "disable",
      enable: "enable",
      connect: "connect",
      disconnect: "disconnect",
      tokenFor: (name: string) => `Token for ${name}`,
      bearerPlaceholder: "bearer token",
      setToken: "set token",
    },
    tools: {
      empty: "no tools",
      enableTool: (name: string) => `Enable ${name}`,
      enabled: "enabled",
      schema: "schema",
      argsFor: (name: string) => `Arguments for ${name}`,
      toolError: "the tool returned an error",
    },
    skills: {
      badge: { modified: "modified", missing: "file missing" },
      deleteConfirm: (name: string) => `delete skill "${name}"?`,
      registryBanner: "Skills are a registry; they run once an orchestrator agent exists (S6b).",
      nameAria: "Skill name",
      namePlaceholder: "name (optional — otherwise from SKILL.md)",
      descriptionAria: "Skill description",
      scopeAria: "Scope",
      chooseSkillMd: "choose SKILL.md",
      addSkill: "+ skill",
      empty: "no skills",
    },
    log: {
      limitMustBeNumber: "the limit must be a number",
      limitsTitle: "Limits (spend/rate)",
      scopeAria: "Scope",
      refIdAria: "Project or server ID",
      refIdNotRequired: "not required",
      refIdPlaceholder: "project/server id",
      spendCapAria: "Spend cap, USD",
      spendCapPlaceholder: "cap $ (empty = no limit)",
      ratePerMinAria: "Calls-per-minute limit",
      ratePerMinPlaceholder: "calls/min (empty = no limit)",
      setLimit: "set limit",
      noLimits: "no limits set",
      thScope: "scope",
      thCap: "cap $",
      thRate: "calls/min",
      callsTitle: "Calls",
      noCalls: "no calls",
      thSource: "source",
      thTool: "tool",
      thStatus: "status",
      thLatency: "latency, ms",
      thCost: "cost, $",
      thTime: "time",
      auditTitle: "Audit",
      noAudit: "no audit records",
      thAction: "action",
      thDecision: "decision",
      thReason: "reason",
    },
  },

  // ── storage-degraded banners (spec D3 wire; consumed by the P3 banner) ───────────────────────
  storage: {
    recovered: (path: string) =>
      `Database was corrupted and has been reset. The damaged copy was saved to ${path}.`,
    inMemory: "Storage unavailable — running in memory. Changes will NOT survive a restart.",
  },
} as const;
